[package]
name = "cache_runtime_connection"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
deadpool-redis = "0.22.0"
rdkafka = "0.38.0"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
